### Create account for a customer
POST http://localhost:8080/create/account/
Content-Type: application/json

{
  "customerName": "Sara Mohammadi",
  "nationalId": "1111222234",
  "birthDate": "1992-03-20T00:00:00.000Z",
  "customerType": "NATURALPERSION",
  "phoneNumber": "09111222233",
  "address": "Isfahan, Chahar Bagh Street",
  "postalCode": "8173654321"
}

### get all accounts
GET http://localhost:8080/create/account/all

### change the account date
PUT http://localhost:8080/create/account/1111222233
Content-Type: application/json

{
  "customerName": "Sara Mohammadi Updated",
  "nationalId": "1111222234",
  "birthDate": "1992-03-20T00:00:00.000Z",
  "customerType": "NATURALPERSION",
  "phoneNumber": "09999888777",
  "address": "Isfahan, New Address, Enghelab Street",
  "postalCode": "8173111111",
  "accountStatus": "ACTIVE"
}

### find the account by account number
GET http://localhost:8080/create/account/accountNumber/95341342467317

### find the account number by national id
GET http://localhost:8080/create/account/nationalID/1111222234