### Create account for a customer
POST http://localhost:8080/create/account/
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM0

{
  "customerName": "Sara Mohammadi",
  "nationalId": "1111222234",
  "birthDate": "1992-03-20T00:00:00.000Z",
  "customerType": "NATURALPERSION",
  "phoneNumber": "09111222233",
  "address": "Isfahan, Chahar Bagh Street",
  "postalCode": "8173654321"
}

### change the account date ( name, customer type, phone number, address, postal code, account status)
PUT http://localhost:8080/create/account/1111222234
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM0

{
  "customerName": "Sara Mohammadi Updated",
  "nationalId": "1111222234",
  "birthDate": "1992-03-20T00:00:00.000Z",
  "customerType": "LEGALPERSON",
  "phoneNumber": "09999888777",
  "address": "Isfahan, New Address, Enghelab Street",
  "postalCode": "8173111112",
  "accountStatus": "BLOCKED"
}


### create account for another customer
POST http://localhost:8080/create/account/
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM0

{
  "customerName": "Ali Rezaei",
  "nationalId": "2222333344",
  "birthDate": "1985-07-15T00:00:00.000Z",
  "customerType": "NATURALPERSION",
  "phoneNumber": "09335556677",
  "address": "Tehran, Valiasr Street",
  "postalCode": "1134567890"
}

### get all accounts
GET http://localhost:8080/create/account/all
Authorization: Basic YWRtaW46YWRtaW4xMjM0


### find the account by account number
GET http://localhost:8080/create/account/accountNumber/60753464451321
Authorization: Basic YWRtaW46YWRtaW4xMjM0


### find the account number by national id
GET http://localhost:8080/create/account/nationalID/1111222234
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### get the account balance by account number
GET http://localhost:8080/create/account/balance/60753464451321
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### deposit money to the account
POST http://localhost:8080/Transaction
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM0

{
  "transactionType": "DEPOSIT",
  "accountNumber": "12474331003340",
  "amount": 2500000000.00
}

### withdraw money from the account
POST http://localhost:8080/Transaction
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM0

{
  "transactionType": "WITHDRAW",
  "accountNumber": "12474331003340",
  "amount": 250000.00
}

### transfer money from one account to another
POST http://localhost:8080/Transaction/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM0

{
  "transactionType": "TRANSFER",
  "fromAccount": "60753464451321",
  "toAccount": "12474331003340",
  "amount": 1500000000000.00
}

### get transaction by tracking code
GET http://localhost:8080/Transaction/2
Authorization: Basic YWRtaW46YWRtaW4xMjM0


### 1. Get all transactions for a specific account
GET http://localhost:8080/Transaction/history?accountNumber=69585518378115
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### 2. Get transactions with date range
GET http://localhost:8080/Transaction/history?accountNumber=28589769858450&fromDate=2024-03-21&toDate=2024-09-23
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### 3. Get transactions with amount filter
GET http://localhost:8080/Transaction/history?accountNumber=49785737311071&minAmount=1000000&maxAmount=100000000
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### 4. Get last 100 deposit transactions
GET http://localhost:8080/Transaction/history?accountNumber=28589769858450&transactionType=DEPOSIT&size=100&page=0&sortBy=date&sortDir=desc
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### 5. Get paginated results
GET http://localhost:8080/Transaction/history?accountNumber=40789221480765&page=1&size=5
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### 6. Complex filter: TRANSFER transactions over 500 in last month
GET http://localhost:8080/Transaction/history?accountNumber=28589769858450&transactionType=TRANSFER&minAmount=500&fromDate=2024-08-01
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### 7. Get all transactions from a specific source account
GET http://localhost:8080/Transaction/history?sourceAccountNumber=43318537612452
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### 8. Get all transactions to a specific destination account
GET http://localhost:8080/Transaction/history?destinationAccountNumber=69585518378115
Authorization: Basic YWRtaW46YWRtaW4xMjM0
