services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    restart: unless-stopped

  oracle-db:
    image: wnameless/oracle-xe-11g-r2
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "8081:8080"
    environment:
      - ORACLE_ALLOW_REMOTE=true
    restart: unless-stopped
    # This Oracle image is only ~150MB

volumes:
  oracle-data: