services:
    oracle-db:
        image: gvenzl/oracle-xe:21-slim
        container_name: oracle-db
        ports:
            - "1521:1521"
        environment:
            - ORACLE_PASSWORD=oracle123
            - APP_USER=mohaimen
            - APP_USER_PASSWORD=mohaimen123
        restart: unless-stopped
        volumes:
            - oracle-data:/opt/oracle/oradata

volumes:
    oracle-data: